language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install: 
  - pip install pandas
  - pip install git+https://github.com/jakeee51/GeoLiberator
script:
  - python3 GL_tests.py
before_deploy:
  - python3 poppypib.py
deploy:
  provider: pypi
  username: "__token__"
  password: PYPI_PASSWORD
  edge: true